title: MADELINE'S
description: Madeline's is a bar, restaurant, and events space in Greenpoint,
  BK. It has 2 floors and a private events room. Walk-ins are always welcome.
  Plan your next event here.
