backend:
  name: git-gateway
  branch: main
media_folder: "/assets/images/uploads"

collections:
  - name: "general"
    label: "General"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "index.markdown"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: default"}
          - label: "Menu Categories"
            name: "menu"
            widget: "list"
            fields:
              - {label: Category, name: category-header, widget: string}
              - label: "Subsection"
                name: "subsections"
                widget: "list"
                fields: 
                - {label: Subsection, name: subsection-header, widget: string}
                - label: "Menu Item"
                  name: "items"
                  widget: "list"
                  fields:
                  - {label: Name, name: name, widget: string}
                  - {label: Price, name: price, widget: string}
                  - {label: Description, name: description, widget: string}
                  - {label: Note, name: note, widget: string}